language: node_js
node_js:
- '12.22.12'
env:
  global:
  - DEPLOY_REPOSITORY="git@github.com:konnectors/viasante.git"
  - secure: ITprQ5/I9yrMZrkjSaaT87VT01pUtY9QLhTt+soSdcvetbWXw+CwiykzM1e6vIAlRHRJgxDN/pcX0gbvNaAAKAe8MGlsOTdMojE1PHVoYsThHkm4xqoZXzwNMAwjiBSwoPCKzgqMgXhrZlvad5Z566pq7/ZxVrsVGAV8ZblhlIHHt1euGqgLpfQW+bUqxy+sXrPMaGEze/OfubM++Zi+lp30QTDZk7xbBh/uQiZ2oAGTN0eSkA/VQe1Kd5tJIrvbqXU+tlSmP4xNZuqc0QW6v6RjRiUCKlBt0d6gAlNY19bh6lphME/Hoeyq5zEx/iBrCHz8r7CDuX+K8jW+vGh0szDBwEJ2PbZemDuAbycLcbROWBKtRoMiyrIdeHiwXyWGT2SlMUwY9SQL0zrZK2czh0MAYs0rH9rr6dtOELdsTxdRH8i2HGQVbaaovnUW1wzEePhoB5grv7Epm2WWU9MR+NyOm9sH5PmscxURdhHWLzpJbFBKonJNswYm1Pj5WwrzIrDbtfElekUCxwcHT1I+9LLx64Cn/qBMS83ySrWXR0YncgKBbKAFwerHZkMNFLUs94hmTUwAmchZjvoC3Nx7CjPYyAX1QwrbKihhWFWSks36ndoDE7iPShkbnBA/Ou+XE06UgmhKhyxdOetv+i/VanfZ5vdJA9GSognFDudV3ZY=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_28a6caf02e74_key -iv $encrypted_28a6caf02e74_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
